try _ catch
    1. 소스 상에서 예상되는 오류가 있을때
    2. 예상되는 오류가 발생한 경우 후속 처리를 위해서 미리 정의 해 놓는 구문

        -서비스가 되고 있는 웹사이트


try {
    // 요류가 예상되는 구간

    // 오류가 발생하거나 또는 발생시키면 catch로 유입
    throw Error 객체
} catch (err) {
    // 오류가 발생하면(throw 에러 객체) 유입
    // 오류에 대한 후속 처리

}

예)

try {
    const num = 9;
    if (num % 2==1) { //홀수 일대 오류발생
        throw "짝수만 가능합니다~!!";
    }
} catch (err) {
    console.error(err);
}

Error 생성자 -> 생성해서 throw
    .message -> new Error("오류메세지")
    